### ISSUE TITLE
Request: ability to specify destination file/folders

### ISSUE THREAD

**Issue by vaughnkoch** [singer-io/target-csv#15]
Right now, the default is to create a csv for every schema target-csv receives, with a timestamp in the filename.

It would be great to have a config file that looked like this:
```
{
    "destination_path": "mydatafolder",
    "filename": "{schema}.csv",
    "delimiter": "\t",
    "quotechar": "'"
}
```

**Comment by timvisher** [comment]
This seems to have died on the vine. Please feel free to reopen if you're interested in working on it.
