### ISSUE TITLE
Use parse_message from singer-python 0.2.1

### ISSUE THREAD

**Issue by mdelaurentis** [singer-io/target-csv#2]
We've added a function to parse messages to singer-python 0.2.1. We should change the tap to use it, here: https://github.com/singer-io/target-csv/blob/master/target_csv.py#L54

**Comment by timvisher** [comment]
@joaomarcosgris Is there any chance you'd be willing to contribute you `master` branch as a PR? That would fix this as well as a add a few nice to haves it looks like. :)

**Comment by joaomarcosgris** [comment]
Of course! Nice to see this repo getting updates again :)
